<a href="https://colab.research.google.com/github/leesochang/Deeplearning2020/blob/master/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%EA%B0%9C%EB%A1%A0_Math_20142224_%EC%9D%B4%EC%86%8C%EC%B0%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [9]:
a = np.array([[4, -3, 2], [4, 0, -5]])
print(a)

[[ 4 -3  2]
 [ 4  0 -5]]


In [10]:
a.shape

(2, 3)

In [11]:
b = np.array([[3], [1], [2]])
print(b)

[[3]
 [1]
 [2]]


In [12]:
c = np.matmul(a, b)
print(c)

[[13]
 [ 2]]


In [13]:
d = np.dot(a, b)
print(d)

[[13]
 [ 2]]


In [14]:
c.shape

(2, 1)

In [15]:
d.shape

(2, 1)