<a href="https://colab.research.google.com/github/leesochang/Deeplearning2020/blob/master/%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5%EA%B0%9C%EB%A1%A0_hello_logistic_regression_20142224_%EC%9D%B4%EC%86%8C%EC%B0%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression 이해하기 : 매우 중요

In [39]:
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [40]:
import numpy as np
import matplotlib.pyplot as plt

In [41]:
x_data = [[1,2], [2,3], [3,1], [4,3], [5,3], [6,2]] #1일동안 2시간 공부~ 6일동안 2시간 공부
y_data = [[0],[0],[0],[1],[1],[1]] #눈치껏 추가...?

In [42]:
np.shape(x_data)

(6, 2)

In [43]:
X = tf.placeholder(tf.float32, shape=[None, 2])  #placeholder 데이터를 넣어주는 곳
Y = tf.placeholder(tf.float32, shape=[None, 1])
 
# input = 2, output = 1 
W = tf.Variable(tf.random_normal([2,1]), name='weight')
# output = 1
b = tf.Variable(tf.random_normal([1]), name='bias')

### Hypothesis

In [44]:
# sigmoid function 은 우리의 가설 H(X) = 1/(1+e^(-w.transpose * X))
# tf.div(1., tf.exp(tf.matmul(X, W) + b)) 와 같음
# H 라고 표현
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
#hypothesis = tf.div(1., tf.exp(tf.matmul(X, W) + b)) #이거 사용하면 아래 텐서플로우에 데이터를 넣으면 nan이라는 글이 나옴

In [45]:
# 새롭게 정의된 오차함수
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * (tf.log(1 - hypothesis)))
 
# 학습 그래프 최적화 알고리즘 경사하강법
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

In [46]:
# 예측값 H(X) > 0.5 is true, else false (니가 한 번 맞춰봐라)
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
# 0이나 1의 값을 트레이닝 횟수만큼 평균치 계산 (정확도)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

### Train !

In [47]:
sess = tf.InteractiveSession()

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1751: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [48]:
sess.run(tf.global_variables_initializer())

In [49]:
vcost = []

In [50]:
#숫자가 줄어드는 경향이 중요
for step in range(10001):
    cost_val,  _ = sess.run([cost, train], feed_dict={X:x_data, Y:y_data}) #이 지점에서 tf 넣어줌
    vcost.append(cost_val)
    if step % 1000 == 0:
        print(step, '\t', cost_val)

0 	 0.8427616
1000 	 0.45193925
2000 	 0.38106444
3000 	 0.32594642
4000 	 0.28292093
5000 	 0.24898534
6000 	 0.22184171
7000 	 0.19979829
8000 	 0.18162799
9000 	 0.16643979
10000 	 0.15358135


### Test !

In [53]:
sess.run(hypothesis,feed_dict={X:[[1,2]]} ) 

array([[0.03247718]], dtype=float32)

In [54]:
sess.run(predicted,feed_dict={X:[[1,2]]} )

array([[0.]], dtype=float32)

In [55]:
sess.run(hypothesis,feed_dict={X:[[4,3]]} ) 

array([[0.77765715]], dtype=float32)

In [56]:
sess.run(predicted,feed_dict={X:[[4,3]]} )

array([[1.]], dtype=float32)

In [57]:
sess.run(hypothesis,feed_dict={X:[[1,0.2]]} ) 

array([[0.01940913]], dtype=float32)

In [58]:
sess.run(predicted,feed_dict={X:[[1,0.2]]} )

array([[0.]], dtype=float32)